"""Transparent residual policy baseline for the MuJoCo force task.

The policy predicts a bounded correction to the existing PI command. Training
targets are generated by an oracle PI controller that sees the true contact
force, while the deployed baseline sees the noisy measurement. This keeps the
first learning comparison interpretable and avoids direct hardware commands.
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import shutil
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path
from collections import deque
from typing import Any

import mujoco
import numpy as np
import yaml

from .contact_force_baseline import MODEL_XML, ForceTrackingMetrics, _normal_force, run
from .experiment import REPOSITORY_ROOT, load_config, package_snapshot


@dataclass(frozen=True)
class ResidualDataset:
    """Episode-labelled features and residual targets."""

    features: np.ndarray
    targets: np.ndarray
    episode_ids: np.ndarray

    def __post_init__(self) -> None:
        if self.features.ndim != 2 or self.targets.ndim != 1 or self.episode_ids.ndim != 1:
            raise ValueError("dataset arrays must be a 2D feature matrix and 1D vectors")
        if len(self.features) != len(self.targets) or len(self.features) != len(self.episode_ids):
            raise ValueError("dataset arrays must have the same number of rows")

    def save(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        np.savez_compressed(path, features=self.features, targets=self.targets, episode_ids=self.episode_ids)

    @classmethod
    def load(cls, path: Path) -> "ResidualDataset":
        with np.load(path) as archive:
            return cls(
                features=np.asarray(archive["features"], dtype=np.float64),
                targets=np.asarray(archive["targets"], dtype=np.float64),
                episode_ids=np.asarray(archive["episode_ids"], dtype=np.int64),
            )


@dataclass(frozen=True)
class ResidualLinearPolicy:
    """Ridge-regression residual policy with an explicit output bound."""

    weights: np.ndarray
    residual_limit_n: float = 10.0

    @classmethod
    def fit(cls, features: np.ndarray, targets: np.ndarray, ridge: float = 1e-3, residual_limit_n: float = 10.0) -> "ResidualLinearPolicy":
        if features.ndim != 2 or targets.ndim != 1 or len(features) != len(targets):
            raise ValueError("features must be 2D and targets must be a matching 1D vector")
        if len(features) == 0:
            raise ValueError("cannot fit a policy on an empty dataset")
        if ridge < 0 or residual_limit_n <= 0:
            raise ValueError("ridge must be non-negative and residual_limit_n must be positive")
        design = np.column_stack([features, np.ones(len(features))])
        regularizer = np.eye(design.shape[1], dtype=np.float64) * ridge
        regularizer[-1, -1] = 0.0
        weights = np.linalg.solve(design.T @ design + regularizer, design.T @ targets)
        return cls(weights=weights, residual_limit_n=residual_limit_n)

    def predict(self, features: np.ndarray) -> np.ndarray:
        design = np.column_stack([features, np.ones(len(features))])
        return np.clip(design @ self.weights, -self.residual_limit_n, self.residual_limit_n)

    def save(self, path: Path) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        np.savez_compressed(path, weights=self.weights, residual_limit_n=self.residual_limit_n)

    @classmethod
    def load(cls, path: Path) -> "ResidualLinearPolicy":
        with np.load(path) as archive:
            return cls(
                weights=np.asarray(archive["weights"], dtype=np.float64),
                residual_limit_n=float(archive["residual_limit_n"]),
            )


def _make_system(damping_scale: float, actuator_gain: float, friction_scale: float = 1.0) -> tuple[mujoco.MjModel, mujoco.MjData]:
    if damping_scale <= 0 or actuator_gain <= 0 or friction_scale <= 0:
        raise ValueError("damping_scale, actuator_gain, and friction_scale must be positive")
    model = mujoco.MjModel.from_xml_string(MODEL_XML)
    model.dof_damping[0] *= damping_scale
    model.actuator_gear[0, 0] *= actuator_gain
    model.geom_friction[:, 0] *= friction_scale
    data = mujoco.MjData(model)
    data.qpos[0] = -0.149
    mujoco.mj_forward(model, data)
    return model, data


def _pi_action(
    target_force_n: float,
    force_n: float,
    velocity: float,
    integral_error: float,
    *,
    kp: float,
    ki: float,
    kd: float,
    integral_limit: float,
    control_limit_n: float,
    dt: float,
) -> tuple[float, float]:
    error = target_force_n - force_n
    integral_error = float(np.clip(integral_error + error * dt, -integral_limit, integral_limit))
    control = -(kp * error + ki * integral_error + kd * velocity)
    return float(np.clip(control, -control_limit_n, control_limit_n)), integral_error


def _features(target_force_n: float, measured_force_n: float, velocity: float, integral_error: float, base_control: float) -> np.ndarray:
    return np.asarray(
        [target_force_n - measured_force_n, velocity, integral_error, base_control, target_force_n],
        dtype=np.float64,
    )


def collect_dataset(
    episodes: int = 8,
    steps: int = 500,
    target_force_n: float = 5.0,
    force_noise_std_n: float = 0.2,
    damping_scale: float = 1.5,
    actuator_gain: float = 0.8,
    friction_scale: float = 1.0,
    target_force_range_n: tuple[float, float] | None = None,
    kp: float = 0.5,
    ki: float = 5.0,
    kd: float = 0.3,
    integral_limit: float = 10.0,
    control_limit_n: float = 30.0,
    dynamics_randomization: tuple[tuple[float, float], tuple[float, float]] | None = None,
    actuator_delay_steps: int = 0,
    seed: int = 42,
) -> ResidualDataset:
    """Collect noisy-baseline states and oracle-minus-baseline actions."""
    if episodes < 1 or steps < 10:
        raise ValueError("episodes must be positive and steps must be at least 10")
    if force_noise_std_n < 0:
        raise ValueError("force_noise_std_n must be non-negative")
    if actuator_delay_steps < 0:
        raise ValueError("actuator_delay_steps must be non-negative")
    if dynamics_randomization is not None:
        for low, high in dynamics_randomization:
            if low <= 0 or high < low:
                raise ValueError("dynamics randomization bounds must be positive and ordered")
    if target_force_range_n is not None:
        low, high = target_force_range_n
        if low <= 0 or high < low:
            raise ValueError("target_force_range_n must be positive and ordered")
    rng = np.random.default_rng(seed)
    feature_rows: list[np.ndarray] = []
    target_rows: list[float] = []
    episode_rows: list[int] = []
    for episode_id in range(episodes):
        episode_target_force_n = target_force_n
        if target_force_range_n is not None:
            episode_target_force_n = float(rng.uniform(*target_force_range_n))
        episode_damping, episode_gain = damping_scale, actuator_gain
        if dynamics_randomization is not None:
            episode_damping = float(rng.uniform(*dynamics_randomization[0]))
            episode_gain = float(rng.uniform(*dynamics_randomization[1]))
        model, data = _make_system(episode_damping, episode_gain, friction_scale)
        dt = model.opt.timestep
        baseline_integral = 0.0
        oracle_integral = 0.0
        command_queue: deque[float] = deque([0.0] * actuator_delay_steps)
        for _ in range(steps):
            true_force_n = _normal_force(model, data)
            measured_force_n = max(0.0, true_force_n + float(rng.normal(0.0, force_noise_std_n)))
            base_control, baseline_integral = _pi_action(
                episode_target_force_n, measured_force_n, float(data.qvel[0]), baseline_integral,
                kp=kp, ki=ki, kd=kd, integral_limit=integral_limit,
                control_limit_n=control_limit_n, dt=dt,
            )
            oracle_control, oracle_integral = _pi_action(
                episode_target_force_n, true_force_n, float(data.qvel[0]), oracle_integral,
                kp=kp, ki=ki, kd=kd, integral_limit=integral_limit,
                control_limit_n=control_limit_n, dt=dt,
            )
            feature_rows.append(_features(episode_target_force_n, measured_force_n, float(data.qvel[0]), baseline_integral, base_control))
            target_rows.append(oracle_control - base_control)
            episode_rows.append(episode_id)
            command_queue.append(base_control)
            data.ctrl[0] = command_queue.popleft()
            mujoco.mj_step(model, data)
    return ResidualDataset(
        features=np.asarray(feature_rows, dtype=np.float64),
        targets=np.asarray(target_rows, dtype=np.float64),
        episode_ids=np.asarray(episode_rows, dtype=np.int64),
    )


def split_by_episode(dataset: ResidualDataset, train_fraction: float = 0.8) -> tuple[ResidualDataset, ResidualDataset]:
    """Split by complete episodes to prevent adjacent-timestep leakage."""
    if not 0.0 < train_fraction < 1.0:
        raise ValueError("train_fraction must be between 0 and 1")
    episodes = np.unique(dataset.episode_ids)
    if len(episodes) < 2:
        raise ValueError("at least two episodes are required for a train/test split")
    train_count = max(1, min(len(episodes) - 1, int(np.floor(len(episodes) * train_fraction))))
    train_episodes = set(episodes[:train_count].tolist())
    train_mask = np.asarray([episode_id in train_episodes for episode_id in dataset.episode_ids])
    return (
        ResidualDataset(dataset.features[train_mask], dataset.targets[train_mask], dataset.episode_ids[train_mask]),
        ResidualDataset(dataset.features[~train_mask], dataset.targets[~train_mask], dataset.episode_ids[~train_mask]),
    )


def evaluate_residual(
    policy: ResidualLinearPolicy,
    *,
    steps: int = 1000,
    target_force_n: float = 5.0,
    force_noise_std_n: float = 0.2,
    damping_scale: float = 1.5,
    actuator_gain: float = 0.8,
    friction_scale: float = 1.0,
    kp: float = 0.5,
    ki: float = 5.0,
    kd: float = 0.3,
    integral_limit: float = 10.0,
    control_limit_n: float = 30.0,
    actuator_delay_steps: int = 0,
    feature_indices: tuple[int, ...] | None = None,
    seed: int = 123,
) -> ForceTrackingMetrics:
    """Evaluate PI plus a bounded residual under the same disturbance contract."""
    if steps < 10 or force_noise_std_n < 0 or actuator_delay_steps < 0:
        raise ValueError("steps must be at least 10 and force noise must be non-negative")
    rng = np.random.default_rng(seed)
    model, data = _make_system(damping_scale, actuator_gain, friction_scale)
    dt = model.opt.timestep
    integral_error = 0.0
    forces: list[float] = []
    measured_forces: list[float] = []
    controls: list[float] = []
    penetrations: list[float] = []
    command_queue: deque[float] = deque([0.0] * actuator_delay_steps)
    for _ in range(steps):
        true_force_n = _normal_force(model, data)
        measured_force_n = max(0.0, true_force_n + float(rng.normal(0.0, force_noise_std_n)))
        base_control, integral_error = _pi_action(
            target_force_n, measured_force_n, float(data.qvel[0]), integral_error,
            kp=kp, ki=ki, kd=kd, integral_limit=integral_limit,
            control_limit_n=control_limit_n, dt=dt,
        )
        feature = _features(target_force_n, measured_force_n, float(data.qvel[0]), integral_error, base_control)
        if feature_indices is not None:
            if not feature_indices or any(index < 0 or index >= len(feature) for index in feature_indices):
                raise ValueError("feature_indices must contain valid feature positions")
            feature = feature[list(feature_indices)]
        residual = float(policy.predict(feature[None, :])[0])
        applied_control = float(np.clip(base_control + residual, -control_limit_n, control_limit_n))
        command_queue.append(applied_control)
        data.ctrl[0] = command_queue.popleft()
        mujoco.mj_step(model, data)
        forces.append(true_force_n)
        measured_forces.append(measured_force_n)
        controls.append(applied_control)
        penetrations.append(max(0.0, float(-(data.qpos[0] + 0.15))))
    tail_start = max(0, int(steps * 0.8))
    tail = np.asarray(forces[tail_start:], dtype=np.float64)
    measured_tail = np.asarray(measured_forces[tail_start:], dtype=np.float64)
    return ForceTrackingMetrics(
        target_force_n=target_force_n,
        mean_force_n=float(tail.mean()),
        force_rmse_n=float(np.sqrt(np.mean((tail - target_force_n) ** 2))),
        force_std_n=float(tail.std()),
        measured_force_rmse_n=float(np.sqrt(np.mean((measured_tail - target_force_n) ** 2))),
        measured_force_std_n=float(measured_tail.std()),
        max_abs_control_n=float(np.max(np.abs(controls))),
        max_penetration_m=float(max(penetrations)),
        contacts_seen=bool(np.any(np.asarray(forces) > 0)),
    )


def _mapping(config: dict[str, Any], key: str) -> dict[str, Any]:
    value = config.get(key, {})
    if not isinstance(value, dict):
        raise ValueError(f"{key} must be a mapping")
    return value


def _pair(value: Any, name: str) -> tuple[float, float]:
    if not isinstance(value, (list, tuple)) or len(value) != 2:
        raise ValueError(f"{name} must contain two values")
    return float(value[0]), float(value[1])


def _config_values(config: dict[str, Any]) -> dict[str, Any]:
    """Extract and validate all experiment values from the resolved YAML."""
    task = _mapping(config, "task")
    controller = _mapping(config, "controller")
    disturbance = _mapping(config, "disturbance")
    learning = _mapping(config, "learning")
    evaluation = _mapping(config, "evaluation")
    target_range = _pair(learning.get("train_target_force_range_n", [3.0, 7.0]), "learning.train_target_force_range_n")
    values: dict[str, Any] = {
        "target_force_n": float(task.get("target_force_n", 5.0)),
        "force_noise_std_n": float(disturbance.get("force_noise_std_n", 0.0)),
        "damping_scale": float(disturbance.get("damping_scale", 1.0)),
        "actuator_gain": float(disturbance.get("actuator_gain", 1.0)),
        "friction_scale": float(disturbance.get("friction_scale", 1.0)),
        "actuator_delay_steps": int(disturbance.get("actuator_delay_steps", 0)),
        "kp": float(controller.get("kp", 0.5)),
        "ki": float(controller.get("ki", 5.0)),
        "kd": float(controller.get("kd", 0.3)),
        "integral_limit": float(controller.get("integral_limit", 10.0)),
        "control_limit_n": float(controller.get("control_limit_n", 30.0)),
        "episodes": int(learning.get("episodes", 8)),
        "steps": int(learning.get("steps_per_episode", 500)),
        "ridge": float(learning.get("ridge", 1e-3)),
        "train_fraction": float(learning.get("train_fraction_by_episode", 0.8)),
        "residual_limit_n": float(learning.get("residual_limit_n", 10.0)),
        "target_range": target_range,
        "eval_steps": int(evaluation.get("steps", 1000)),
        "eval_seed": int(evaluation.get("seed", 123)),
    }
    randomization = learning.get("dynamics_randomization")
    if randomization is not None:
        if not isinstance(randomization, dict):
            raise ValueError("learning.dynamics_randomization must be a mapping")
        values["dynamics_randomization"] = (
            _pair(randomization.get("damping_scale"), "learning.dynamics_randomization.damping_scale"),
            _pair(randomization.get("actuator_gain"), "learning.dynamics_randomization.actuator_gain"),
        )
    else:
        values["dynamics_randomization"] = None
    if values["target_force_n"] <= 0 or values["force_noise_std_n"] < 0:
        raise ValueError("target force must be positive and noise must be non-negative")
    return values


def run_from_config(config: dict[str, Any], artifact_dir: Path, *, seed: int | None = None, episodes: int | None = None,
                    steps: int | None = None, eval_steps: int | None = None,
                    force_noise_std_n: float | None = None) -> dict[str, Any]:
    """Run the complete dataset/training/evaluation loop from resolved YAML."""
    values = _config_values(config)
    if force_noise_std_n is not None:
        if force_noise_std_n < 0:
            raise ValueError("force_noise_std_n must be non-negative")
        values["force_noise_std_n"] = float(force_noise_std_n)
    actual_seed = int(seed if seed is not None else config.get("experiment", {}).get("seed", 42))
    dataset = collect_dataset(
        episodes=int(episodes if episodes is not None else values["episodes"]),
        steps=int(steps if steps is not None else values["steps"]),
        target_force_n=values["target_force_n"],
        force_noise_std_n=values["force_noise_std_n"],
        damping_scale=values["damping_scale"], actuator_gain=values["actuator_gain"],
        friction_scale=values["friction_scale"],
        target_force_range_n=values["target_range"],
        kp=values["kp"], ki=values["ki"], kd=values["kd"],
        integral_limit=values["integral_limit"], control_limit_n=values["control_limit_n"],
        dynamics_randomization=values["dynamics_randomization"],
        actuator_delay_steps=values["actuator_delay_steps"], seed=actual_seed,
    )
    train, test = split_by_episode(dataset, values["train_fraction"])
    policy = ResidualLinearPolicy.fit(train.features, train.targets, ridge=values["ridge"], residual_limit_n=values["residual_limit_n"])
    eval_count = int(eval_steps if eval_steps is not None else values["eval_steps"])
    baseline = run(steps=eval_count, target_force_n=values["target_force_n"], force_noise_std_n=values["force_noise_std_n"],
                   damping_scale=values["damping_scale"], actuator_gain=values["actuator_gain"], friction_scale=values["friction_scale"],
                   actuator_delay_steps=values["actuator_delay_steps"], kp=values["kp"], ki=values["ki"], kd=values["kd"],
                   integral_limit=values["integral_limit"], control_limit_n=values["control_limit_n"], seed=values["eval_seed"])
    residual = evaluate_residual(policy, steps=eval_count, target_force_n=values["target_force_n"], force_noise_std_n=values["force_noise_std_n"],
                                 damping_scale=values["damping_scale"], actuator_gain=values["actuator_gain"], friction_scale=values["friction_scale"],
                                 actuator_delay_steps=values["actuator_delay_steps"], kp=values["kp"], ki=values["ki"], kd=values["kd"],
                                 integral_limit=values["integral_limit"], control_limit_n=values["control_limit_n"], seed=values["eval_seed"])
    artifact_dir.mkdir(parents=True, exist_ok=False)
    dataset.save(artifact_dir / "dataset.npz")
    policy.save(artifact_dir / "policy.npz")
    manifest = {
        "run_id": artifact_dir.name, "created_at_utc": dt.datetime.now(dt.timezone.utc).isoformat(),
        "config_name": config.get("experiment", {}).get("name"), "config_path": "configs/residual_policy.yaml",
        "git_commit": _git_revision(), "python": sys.version, "slurm_job_id": os.environ.get("SLURM_JOB_ID"),
        "artifact_dir": str(artifact_dir), "seed": actual_seed, "package_snapshot": package_snapshot(),
        "dataset_rows": len(dataset.features), "train_rows": len(train.features), "test_rows": len(test.features),
    }
    (artifact_dir / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    (artifact_dir / "config.yaml").write_text(yaml.safe_dump(config, sort_keys=False), encoding="utf-8")
    metrics = {"test_residual_rmse_n": float(np.sqrt(np.mean((policy.predict(test.features) - test.targets) ** 2))),
               "baseline": asdict(baseline), "residual": asdict(residual)}
    (artifact_dir / "metrics.json").write_text(json.dumps(metrics, indent=2) + "\n", encoding="utf-8")
    return {"manifest": manifest, "metrics": metrics}


def _git_revision() -> str:
    result = subprocess.run(["git", "rev-parse", "HEAD"], cwd=REPOSITORY_ROOT, check=False, capture_output=True, text=True)
    return result.stdout.strip() if result.returncode == 0 else "unavailable"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=Path("configs/residual_policy.yaml"))
    parser.add_argument("--run-id", default=None)
    parser.add_argument("--episodes", type=int)
    parser.add_argument("--steps", type=int)
    parser.add_argument("--eval-steps", type=int)
    parser.add_argument("--seed", type=int)
    parser.add_argument("--noise-std", type=float, help="override disturbance.force_noise_std_n")
    parser.add_argument("--dataset", type=Path, help="deprecated: use the config run artifact")
    parser.add_argument("--policy", type=Path, help="deprecated: use the config run artifact")
    args = parser.parse_args()
    config = load_config(args.config)
    experiment = config.setdefault("experiment", {})
    run_id = args.run_id or experiment.get("run_id") or dt.datetime.now(dt.timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    artifact_root = REPOSITORY_ROOT / str(experiment.get("artifact_root", "artifacts/residual-baseline"))
    output = run_from_config(config, artifact_root / str(run_id), seed=args.seed, episodes=args.episodes, steps=args.steps,
                             eval_steps=args.eval_steps, force_noise_std_n=args.noise_std)
    if args.dataset:
        args.dataset.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(artifact_root / str(run_id) / "dataset.npz", args.dataset)
    if args.policy:
        args.policy.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(artifact_root / str(run_id) / "policy.npz", args.policy)
    print(json.dumps(output, indent=2))


if __name__ == "__main__":
    main()
